### ISSUE TITLE
Goto definition doesn't work

### ISSUE THREAD

**Issue by andersennl** [shanehofstetter/rails-i18n-vscode#6]
Hi, I have a case where hovering the mouse over a WTI key (in a `.html.erb` template) shows the corresponding translation absolutely fine but goto definition on the same key says `No definition found`. 

The translations are located in `config/locales/en.yml`. I'm not sure what additional, helpful information I can provide. Please let me know. Thanks for looking into this.

**Comment by shanehofstetter** [comment]
Hi @andersennl, does the goto-definition generally not work in your setup or just not for some specific translations/locale keys?

**Comment by andersennl** [comment]
I have just tried around six keys, which didn’t work though. The mouse hover thing always worked, though.

**Comment by shanehofstetter** [comment]
could you provide me maybe with a sample of your locale file and maybe a small part of your view file, and where its located? 

Additionally or alternatively, this would also be of help:
1. change the setting `railsI18n.debugLevel` to `0`
2. restart vscode
3. open your developer tools (Help > Toggle Developer Tools), clear all logs
4. reproduce the error 
5. post the logs here

**Comment by andersennl** [comment]
Of course, thanks for looking into this. I'll post the logs below. I just clicked on a wti key (which ended on `.save`), inside a `.html.erb` template. The _go to definition_ took me to a `def save` in a Ruby class. Maybe I've configured something wrong?

The files and paths are:
app/views/external/remote/view_subscription.html.erb
`<%= t "external.remote.view_subscription.save" %>`

config/locales/en.yml
`en.external.remote.view_subscription.save`

Here's the log:
https://gist.github.com/andersennl/5680ae176abe6820130152aca5d6b2f9

I noticed this line with a double `//`:
```
ERR cannot open file:///Users/user/myproject/app/views/external/remote//.html.erb. Detail: File not found (file:///Users/user/myproject/app/views/external/remote//.html.erb)
```

**Comment by shanehofstetter** [comment]
Thanks for detailed information. This seems kinda odd, especially that it seems to open a method definition in a .rb file. Is it possible that some other extension which provides definitions is interfering (maybe test it by disabling them and trying to reproduce the bug)? 
As for the error message, I need to look further into this and where and why it even tries to open a .erb file.

**Comment by andersennl** [comment]
Ok I've made an educated guess and disabled this package https://github.com/rubyide/vscode-ruby, which now prevents VSCode from opening the .rb file. The _goto definition_ of I18n still doesn't work for me, though. I've updated the gist above with a new log (without the mentioned extension). I read through it briefly and saw an error message from your package:
```
ERR Cannot destructure property `key` of 'undefined' or 'null'.: TypeError: Cannot destructure property `key` of 'undefined' or 'null'.
	at I18nHoverProvider.provideHover (/Users/user/.vscode/extensions/shanehofstetter.rails-i18n-0.0.8/out/i18nHoverProvider.js:9:56)
```

**Comment by shanehofstetter** [comment]
That error occurs at the moment when hovering over some text which isn't an i18n key, therefore it should not be a problem (I'll fix it sometime). 

Are your locale keys defined like this? 
```
en:
  external.remote.view_subscription.save: Save
```

If yes, then this would be the reason why the goto-definition does not work. I already looked into it and just published an update which should now fix this. Could you update the extension and let me know if the problem persists?

**Comment by andersennl** [comment]
Sorry, I forgot to mention the `.yml` file structure. It's actually nested like this:
```
en:
  external:
    remote:
      view_subscription:
        save: Save
```

Thanks for the update! Unfortunately the issue remains. I've created a gist with the VSCode logs https://gist.github.com/andersennl/43cb57273047defb00fb86816a493b2f. Thanks again.

I have a not directly related question: I saw that you have a roadmap in the project's readme. If I could make a feature request, it would be awesome to be able to copy a key's path inside the `.yml` file. More precisely: if I place the cursor on the last key in the path `save:` (when in `en.yml`) and then execute a command, I'd like to have `external.remote.view_subscription.save` in my clipboard. This would be super useful for everyone coming from RubyMine. There is an extension which provides this command (https://github.com/CYBAI/vscode-yaml-key-viewer) but unfortunately it's not working well.

**Comment by shanehofstetter** [comment]
Alright, I have another guess: Did you set `railsI18n .loadAllTranslations` to `true` ? If yes, could you try turning it off and trying again (needs a restart)? 
Thanks for the feature request, I will add it to the Roadmap.

**Comment by andersennl** [comment]
Yes it was set to true - I've turned it off but unfortunately it's the same outcome. Shall I provide the logs?
Thanks for adding it to the roadmap 👍

**Comment by shanehofstetter** [comment]
Did you restart VSCode after changing the setting? Yeah maybe the logs might help, would be great if you created a new gist.

**Comment by shanehofstetter** [comment]
I also just released a new update which fixes a problem with the loading of the translations, which only affected the definition provider in some cases and therefore may be the reason why it didn't work.  Could you update the extension and let me know if it helped?

**Comment by andersennl** [comment]
Great, it works with the newest version 👍 (with `railsI18n.loadAllTranslations` set to true.)

Thanks a lot for your help!

**Comment by shanehofstetter** [comment]
Nice! I'm closing this issue then.
